# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-12 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180909_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(default='', verbose_name='课程详情'),
        ),
    ]
